[package]
name = "TokenBridge"
version = "0.0.1"

[dependencies.Sui]
local

[dependencies.Wormhole]
local = "../wormhole"

[addresses]
token_bridge = "_"

[dev-dependencies.Wormhole]
local = "../wormhole"

[dev-addresses]
wormhole = "0x100"
token_bridge = "0x200"
